prefix qb:   <http://purl.org/linked-data/cube#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
prefix sh:   <http://www.w3.org/ns/shacl#> 
prefix skos: <http://www.w3.org/2004/02/skos/core#> 
prefix v:    <http://www.w3.org/2006/vcard/ns#> 
prefix vl:   <https://data.vlaanderen.be/ns/shacl#> 
prefix dcat: <http://www.w3.org/ns/dcat#> 
prefix dct:  <http://purl.org/dc/terms/>

# The catalogue is defined in schemas/infer/catalog.ttl .
# This query adds references from the catalogue to all defined
# datasets and services.
INSERT {
	<htts://data.vlaanderen.be/id/catalog/vsds> dcat:dataset ?dataset .
	<htts://data.vlaanderen.be/id/catalog/vsds> dcat:service ?dataservice .
}
WHERE {
	{?dataset a dcat:Dataset }
	{?dataservice a dcat:DataService }
}

