# Change 2
# https://github.com/Informatievlaanderen/OSLOthema-DCATAPVlaanderen/issues/14
# Dataset - dct:accessRights range incorrect

PREFIX qb:   <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh:   <http://www.w3.org/ns/shacl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX vl:   <https://data.vlaanderen.be/ns/shacl#>
PREFIX v:   <http://www.w3.org/2006/vcard/ns#>

DELETE {
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#DatasetShape/a81035a5dbbdae24651c34e5602a1fe6fe5427a3> sh:class skos:Concept .
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#DataServiceShape/a81035a5dbbdae24651c34e5602a1fe6fe5427a3> sh:class skos:Concept .
}
INSERT {
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#DatasetShape/a81035a5dbbdae24651c34e5602a1fe6fe5427a3> sh:hasValue <http://publications.europa.eu/resource/authority/access-right/PUBLIC> .
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#DataServiceShape/a81035a5dbbdae24651c34e5602a1fe6fe5427a3> sh:hasValue <http://publications.europa.eu/resource/authority/access-right/PUBLIC> .
}
WHERE {}
