# https://github.com/Informatievlaanderen/OSLOthema-DCATAPVlaanderen/issues/14


PREFIX qb:   <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh:   <http://www.w3.org/ns/shacl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX vl:   <https://data.vlaanderen.be/ns/shacl#>
PREFIX v:   <http://www.w3.org/2006/vcard/ns#>

DELETE {
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#CatalogusShape/509740cc7b3c86ebee90dc6303c11c40e2b08212> sh:class <http://purl.org/dc/terms/LicenseDocument> .
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#DataServiceShape/509740cc7b3c86ebee90dc6303c11c40e2b08212> sh:class <http://purl.org/dc/terms/LicenseDocument> .
}
INSERT {
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#CatalogusShape/509740cc7b3c86ebee90dc6303c11c40e2b08212> sh:hasValue <https://data.vlaanderen.be/id/licentie/creative-commons-zero-verklaring/v1.0> .
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#DataServiceShape/509740cc7b3c86ebee90dc6303c11c40e2b08212> sh:hasValue <https://data.vlaanderen.be/id/licentie/creative-commons-zero-verklaring/v1.0> .
}
WHERE {}
