# Change 5
# https://github.com/Informatievlaanderen/OSLOthema-DCATAPVlaanderen/issues/18
# dct:identifier literal validation implementation incorrect


PREFIX qb:   <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh:   <http://www.w3.org/ns/shacl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX vl:   <https://data.vlaanderen.be/ns/shacl#>
PREFIX v:   <http://www.w3.org/2006/vcard/ns#>

DELETE {
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#CatalogusShape/05134c4e7c34157d6f7ac1128713a08418e0fe7d> sh:datatype rdfs:Literal .
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#DatasetShape/05134c4e7c34157d6f7ac1128713a08418e0fe7d> sh:datatype rdfs:Literal .
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#DataServiceShape/05134c4e7c34157d6f7ac1128713a08418e0fe7d> sh:datatype rdfs:Literal .
}
INSERT {
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#CatalogusShape/05134c4e7c34157d6f7ac1128713a08418e0fe7d> sh:nodeKind sh:Literal .
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#DatasetShape/05134c4e7c34157d6f7ac1128713a08418e0fe7d> sh:nodeKind sh:Literal .
  <https://data.vlaanderen.be/shacl/DCAT-AP-VL#DataServiceShape/05134c4e7c34157d6f7ac1128713a08418e0fe7d>  sh:nodeKind sh:Literal .
}
WHERE {}
