# Change 6
# https://github.com/Informatievlaanderen/OSLOthema-DCATAPVlaanderen/issues/19
# Range validation of dct:conformsTo


PREFIX qb:   <http://purl.org/linked-data/cube#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sh:   <http://www.w3.org/ns/shacl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX vl:   <https://data.vlaanderen.be/ns/shacl#>
PREFIX v:   <http://www.w3.org/2006/vcard/ns#>

INSERT {<https://data.vlaanderen.be/shacl/DCAT-AP-VL#DatasetShape/1b8b3557ea1ccbabc0962c345782ae53740e72e1> sh:deactivated true }
WHERE {}
